# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c4cf7d845286f0234b7aca559e2d9b1812fbdff2eb63871851acfe4b8b471df64a75c68a40fbcaa7478f2d0c9443ffcb54037f10addf072ce449244975810f

test:
  secret_key_base: 065e3060e2d5250549fe6c93e3e680d7a51ed8c61717d2c2d73f9ffd033c748bcd4738c3e560248c90170471e7f7829eb96be71564f76d3ca262a1112b3eefb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
